#!/bin/bash

# File: gnuplot-orbit.sh
# Generate orbital data and plot
#
# Author: Paul Schulz <paul@mawsonlakes.org>
# Licence: GPL

# Make use of default format as generated by Roy Duncan's orbit script.

echo 'Generate data (takes some time)'
../contrib/roy/orbit/orbit.pl > orbit.out

echo Pull out position information
cat orbit.out  | \
  grep -v Note | \
  grep -v UTC | \
  awk '{print $5 " " $6 " " $7 "\n" $27 " " $28 " " $29}' \
  > orbit.xyz

# Assumes datafile 'orbit.xyz' exists in current directory and that
# the data is in format x,y,x

gnuplot <<EOF 
set term post eps
set size ratio 1
set style data dots
set output "orbit.ps"
splot "orbit.xyz
quit
EOF